import type { Metadata } from "next";
import { Inter, Poppins, Roboto } from "next/font/google";
import "./globals.css";

const poppins = Poppins({subsets: ['latin'],weight:'400'});
export const metadata: Metadata = {
  title: "Pawonkoe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
